# Generated by Django 4.1.7 on 2023-02-20 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('nacionalidad', models.CharField(choices=[('ARG', 'Argentina'), ('BRA', 'Brasil'), ('COL', 'Colombia'), ('VEN', 'Venezuela'), ('PER', 'Perú'), ('BOL', 'Bolivia'), ('ECU', 'Ecuador'), ('CHI', 'Chile'), ('PAR', 'Paraguay'), ('URU', 'Uruguay')], default='ARG', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('ubicacion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=1000)),
                ('explicacion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='movimientos')),
                ('dificultad', models.CharField(choices=[('facil', 'Facil'), ('normal', 'Normal'), ('dificil', 'Dificil')], default='normal', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Wod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('tipo', models.CharField(choices=[('TABATA', 'TABATA'), ('EMOM', 'EMOM'), ('FOR TIME', 'FOR TIME'), ('AMRAP', 'AMRAP')], default='TABATA', max_length=10)),
                ('duracion', models.IntegerField()),
                ('rondas', models.CharField(choices=[('Sin Rondas', 'Sin Rondas'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='Sin Rondas', max_length=10)),
                ('cantidad1', models.IntegerField(blank=True, default=0)),
                ('cantidad2', models.IntegerField(blank=True, default=0)),
                ('cantidad3', models.IntegerField(blank=True, default=0)),
                ('cantidad4', models.IntegerField(blank=True, default=0)),
                ('cantidad5', models.IntegerField(blank=True, default=0)),
                ('movimiento1', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos1', to='AppCoder.movimiento')),
                ('movimiento2', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos2', to='AppCoder.movimiento')),
                ('movimiento3', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos3', to='AppCoder.movimiento')),
                ('movimiento4', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos4', to='AppCoder.movimiento')),
                ('movimiento5', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos5', to='AppCoder.movimiento')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreCompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('wod1', models.IntegerField()),
                ('wod2', models.IntegerField()),
                ('wod3', models.IntegerField()),
                ('total', models.IntegerField()),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.atleta')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('score', models.IntegerField()),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.atleta')),
                ('wod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.wod')),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='competencias')),
                ('wod1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wod1', to='AppCoder.wod')),
                ('wod2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wod2', to='AppCoder.wod')),
                ('wod3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wod3', to='AppCoder.wod')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('comentario', models.CharField(max_length=300)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.wod')),
            ],
        ),
        migrations.CreateModel(
            name='AvatarImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='avatares')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='atleta',
            name='box',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='box', to='AppCoder.box'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Adaptacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=1000)),
                ('explicacion', models.CharField(max_length=200)),
                ('movimiento', models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, related_name='movimiento', to='AppCoder.movimiento')),
            ],
        ),
    ]
