# Generated by Django 4.1.5 on 2023-02-03 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_remove_estudiante_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiante',
            new_name='Atleta',
        ),
    ]
