# Generated by Django 4.1.7 on 2023-02-20 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_wod_cantidad2_alter_wod_cantidad3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wod',
            name='cantidad4',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wod',
            name='cantidad5',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='wod',
            name='movimiento3',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos3', to='AppCoder.movimiento'),
        ),
        migrations.AlterField(
            model_name='wod',
            name='movimiento4',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos4', to='AppCoder.movimiento'),
        ),
        migrations.AlterField(
            model_name='wod',
            name='movimiento5',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos5', to='AppCoder.movimiento'),
        ),
    ]
