# Generated by Django 4.1.5 on 2023-02-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0009_formulario_formularioprincipal'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioprincipal',
            name='difficulty',
            field=models.CharField(choices=[('facil', 'Facil'), ('normal', 'Normal'), ('dificil', 'Dificil')], default='normal', max_length=10),
        ),
    ]
