# Generated by Django 4.1.5 on 2023-02-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0010_formularioprincipal_difficulty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='dificultad',
            field=models.CharField(choices=[('facil', 'Facil'), ('normal', 'Normal'), ('dificil', 'Dificil')], default='normal', max_length=10),
        ),
    ]
