# Generated by Django 4.1.5 on 2023-02-03 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0011_alter_movimiento_dificultad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wod',
            name='movimientos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.movimiento'),
        ),
    ]
