# Generated by Django 4.1.5 on 2023-02-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0012_alter_wod_movimientos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wod',
            old_name='movimientos',
            new_name='movimiento',
        ),
    ]
