# Generated by Django 4.1.5 on 2023-02-03 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0014_remove_wod_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='wod',
            name='movimientos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppCoder.movimiento'),
            preserve_default=False,
        ),
    ]
