# Generated by Django 4.1.5 on 2023-02-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0015_wod_movimientos'),
    ]

    operations = [
        migrations.AddField(
            model_name='wod',
            name='duracion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
