# Generated by Django 4.1.5 on 2023-02-04 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0016_wod_duracion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wod',
            name='tipo',
            field=models.CharField(choices=[('TABATA', 'TABATA'), ('EMOM', 'EMOM'), ('FOR TIME', 'FOR TIME'), ('AMRAP', 'AMRAP')], default='TABATA', max_length=10),
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('score', models.IntegerField()),
                ('atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.atleta')),
                ('wod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCoder.wod')),
            ],
        ),
    ]
